// ── Scenario context — generated by ScenarioAgent ─────────────────────────
export interface ScenarioContext {
  personaName:    string;
  personaRole:    string;
  setting:        string;
  systemPrompt:   string;
  openingMessage: string;
}

// ── Client → Server ────────────────────────────────────────────────────────
export type ClientMessage =
  | {
      type:            "start_session";
      sessionId:       string;
      language:        string;
      level:           string;
      scenarioRequest: string;
    }
  | {
      type:    "send_message";
      content: string;
    }
  | {
      type: "end_session";
    }
  | {
      type: "ping";
    };

// ── Server → Client ────────────────────────────────────────────────────────
export type ServerMessage =
  | {
      type:     "session_ready";
      scenario: ScenarioContext;
    }
  | {
      type:  "token";
      token: string;
    }
  | {
      type:    "message_done";
      message: {
        id:        string;
        role:      "assistant";
        content:   string;
        createdAt: string;
      };
    }
  | {
      type:    "user_message_saved";
      message: {
        id:        string;
        role:      "user";
        content:   string;
        createdAt: string;
      };
    }
  | {
      type: "session_ended";
    }
  | {
      type:    "error";
      code:    string;
      message: string;
    }
  | {
      type: "pong";
    };
